version: '3'
services:
  db:
    container_name: database
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  web:
    container_name: api-registration-dailymotion
    build: .
    env_file:
        - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python ./api/utils/manage.py && python3 -m flask run --host=0.0.0.0'


  


volumes:
  postgres_data: {}